# Generated by Django 4.1.7 on 2023-05-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField(max_length=255)),
                ('descricacao', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('cat', models.TextField(max_length=255)),
                ('imagem', models.FileField(null=True, upload_to='img')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_disc.categoria')),
            ],
        ),
    ]
