# Generated by Django 4.1.7 on 2023-05-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_disc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
