# Generated by Django 4.1.7 on 2023-05-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disc', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=255)),
                ('categoria', models.TextField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
            ],
        ),
    ]
